### ISSUE TITLE
Unit tests: mirror circuits

### ISSUE THREAD

**Issue by WrathfulSpatula** [unitaryfund/pyqrack#13]
We rely on Qrack library unit tests, but a [random mirror circuit integration test](https://github.com/vm6502q/qrack/blob/12e733cf866eeb9b4996c9558be77858535f59d6/test/tests.cpp#L5954) should be adapted from the underlying Qrack test suite. It can give excellent coverage in a fast test, though it's not modular. At least, it's a tractable atomic step toward PyQrack unit tests and tooling.

**Comment by WrathfulSpatula** [comment]
More generally, we need a PyQrack-specific unit test suite. This is worth a unitaryhack.dev bounty.

**Comment by golanor** [comment]
I've started to look into this, one thing I'm missing is how to create circuits in PyQrack without using Qiskit. Is there a way to do this without supplying gates/loading from file? OR should I install qiskit alongside PyQrack and add it as a test dependency?

**Comment by WrathfulSpatula** [comment]
Historically, Qrack always worked in terms of "immediate" gates on simulator instances, not circuit definitions. To "save a circuit," you would simply write a Qrack program in terms of immediate gates on a simulator.

However, we've recently added `QrackCircuit`. (https://pyqrack.readthedocs.io/en/latest/autoapi/pyqrack/qrack_circuit/index.html)

The point of saving to and loading from file is that you can store the optimized circuit compilation result at all: otherwise, you're still writing a Qrack program, loaded at run time, which is no different from how Qiskit does it, as far as I know.

I would suggest simply writing a program in terms of "immediate" Qrack gates, particularly as `QrackCircuit` might optimize away parts of logical tests you want to check.

**Comment by WrathfulSpatula** [comment]
It's also worth pointing out that here's an example of a mirror circuit integration test, for PyQrack:

https://github.com/unitaryfund/research/blob/main/qrack-report/plots/Qrack_mirror_circuit_validation.ipynb
